name: iOS

on: [pull_request]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout app repo 
      uses: actions/checkout@v2

    - name: Install simulator target
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-apple-ios

    - name: Build
      run: xcodebuild -workspace SuperRustBoy.xcworkspace -scheme SuperRustBoy-iOS -destination platform="iOS Simulator",name="iPhone 8"
