name: iOS

on: [pull_request]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: xcodebuild -scheme SuperRustBoy-iOS -destination platform="iOS Simulator",name="iPhone 8",OS=13.1
