name: iOS

on: [pull_request]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-apple-ios
    - name: Build
      run: xcodebuild -workspace SuperRustBoy.xcworkspace -scheme SuperRustBoy-iOS -destination platform="iOS Simulator",name="iPhone 8"
