name: macOS

on: [pull_request]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout app repo 
      uses: actions/checkout@v2

    - name: Install cargo
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Build
      run: xcodebuild -workspace SuperRustBoy.xcworkspace -scheme SuperRustBoy
